---
#Add user BS
- user:
        name: Beth Smith
        shell: /bin/sh 
        home: /home/beth

- name: Set authorized key
  authorized_key:
        user: Beth Smith
        key: "{{ lookup ('file', '/home/krepin/.ssh/id_rsa.pub') }}"
