---
#Add user MS
- user:
        name: Morty Smith
        shell: /bin/sh 
        home: /var/tmp/morty

- name: Set authorized key
  authorized_key:
        user: Morty Smith
        key: "{{ lookup ('file', '/home/krepin/.ssh/id_rsa.pub') }}"
